spring:
  config:
    import: optional:file:.env
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  frontend:
    origin: ${FRONTEND_URL}
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080