spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/notepadDB # port of the docker postgres
    username: app
    password: password
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080